routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\TimeEntryController;
use App\Http\Controllers\QrcodeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\ProfileController;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::prefix('login')->group(function () {
    Route::get('/', [LoginController::class, 'index'])->name('login');
});

Route::post('/logout', [LoginController::class, 'logout'])->name('logout');


Route::middleware(['auth'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::group(['middleware' => ['role:super-admin|admin']], function () {
        

        Route::prefix('departments')->group(function () {
            Route::get('/', [DepartmentController::class, 'index'])->name('department');
            Route::get('/{id}', [DepartmentController::class, 'show'])->name('department.show');
        });

        Route::prefix('employees')->group(function () {
            Route::get('/', [EmployeeController::class, 'index'])->name('employee');
            Route::get('/{id}', [EmployeeController::class, 'show'])->name('employee.show');
        });

        Route::prefix('time-entries')->group(function () {
            Route::get('/', [TimeEntryController::class, 'index'])->name('time.entries');
            Route::get('/export', [TimeEntryController::class, 'export'])->name('time.export');
        });

        Route::prefix('export')->group(function () {
            Route::get('/', [ExportController::class, 'export'])->name('export');
        });
    });

    Route::group(['middleware' => ['role:super-admin']], function () {
        Route::prefix('admins')->group(function () {
            Route::get('/', [AdminController::class, 'index'])->name('admin');
        });
    });
    
    
    
});

Route::prefix('attendance')->group(function () {
    Route::get('/time-in', [TimeEntryController::class, 'timeIn'])->name('attendance.timein');
    Route::post('/time-in', [TimeEntryController::class, 'timeIn'])->name('attendance.timein');
});



Route::prefix('qr-code')->group(function () {
    Route::get('/scan', [QrcodeController::class, 'index']);
    Route::get('/download/{user_id}', [QrcodeController::class, 'download']);
});

app/Models/TimeEntry.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class TimeEntry extends Model
{
    use HasFactory;

    protected $dates = [
        'time_start_am',
        'time_end_am',
        'time_start_pm',
        'time_end_pm',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'user_id',
        'time_start_am',
        'time_end_am',
        'time_start_pm',
        'time_end_pm',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function setTimeStartAmAttribute($value)
    {
        $this->attributes['time_start_am'] = $value ? Carbon::createFromFormat('Y-m-d H:i', $value)->format('Y-m-d H:i:s') : null;
    }

    public function setTimeEndAmAttribute($value)
    {
        $this->attributes['time_end_am'] = $value ? Carbon::createFromFormat('Y-m-d H:i', $value)->format('Y-m-d H:i:s') : null;
    }

    public function setTimeStartPmAttribute($value)
    {
        $this->attributes['time_start_pm'] = $value ? Carbon::createFromFormat('Y-m-d H:i', $value)->format('Y-m-d H:i:s') : null;
    }

    public function setTimeEndPmAttribute($value)
    {
        $this->attributes['time_end_pm'] = $value ? Carbon::createFromFormat('Y-m-d H:i', $value)->format('Y-m-d H:i:s') : null;
    }

    public function getTimeInAmAttribute()
    {
        return $this->time_start_am ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_start_am) : null;
    }

    public function getTimeOutAmAttribute()
    {
        return $this->time_end_am ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_end_am): null;
    }


    public function getTimeInPmAttribute()
    {
        return $this->time_start_pm ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_start_pm): null;
    }

    public function getTimeOutPmAttribute()
    {
        return $this->time_end_pm ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_end_pm) : null;
    }


    public function getTimeInStatusAttribute()
    {
        $morning = Carbon::create($this->time_start->year, $this->time_start->month, $this->time_start->day, 8, 0, 0);
        $afternoon = Carbon::create($this->time_start->year, $this->time_start->month, $this->time_start->day, 13, 0, 0);

        if($this->time_start->format('A') === 'PM') {
            return $this->time_start->lte($afternoon) ? true : false;
        }else {
            return $this->time_start->lte($morning) ? true : false;
        }
    }

    

    public function getTotalTimeAttribute()
    {
  

        if($this->time_start_am && $this->time_end_pm && !$this->time_end_am) {

            $time_start = $this->time_start_am ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_start_am) : 0;
            $time_end = $this->time_end_pm ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_end_pm) : 0;

            $total = $time_end ?  $time_end->diffInSeconds($time_start) : 0;
            
            $nightShiftStart = $this->time_start_am ? Carbon::create($time_start->year, $time_start->month, $time_start->day, 01, 0, 0) : 0;
            $nightShiftEnd = $this->time_start_am ? Carbon::create($time_start->year, $time_start->month, $time_start->day, 03, 59, 59) : 0;

            if ($time_start->between($nightShiftStart, $nightShiftEnd)) {
                return gmdate("H:i", $total - 28800);
            }else {
                return gmdate("H:i", $total - 3600);
            }

        }else {

            $time_start_am = $this->time_start_am ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_start_am) : 0;
            $time_end_am = $this->time_end_am ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_end_am) : 0;

            $time_start_pm = $this->time_start_pm ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_start_pm) : 0;
            $time_end_pm = $this->time_end_pm ? Carbon::createFromFormat('Y-m-d H:i:s', $this->time_end_pm) : 0;

            $secondsAm =  $time_end_am ?  $time_end_am->diffInSeconds($time_start_am) : 0;
            $secondsPm =  $time_end_pm ?  $time_end_pm->diffInSeconds($time_start_pm) : 0;

            return gmdate("H:i", $secondsAm + $secondsPm);

        }

        
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class EmployeeController extends Controller
{
    public function index()
    {
        return view('pages.employee.index');
    }

    public function show($id)
    {
        $user = User::role('employee')->whereId($id)->firstOrFail();

        return view('pages.employee.show', compact('user'));
    }
}

app/Http/Livewire/Admin/ShowAdmins.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use Illuminate\Support\Arr;
use App\Models\User;


class ShowAdmins extends Component
{
    public $name;
    public $username;
    public $password;
    public $role;
    public $user_id;
    public $updateMode;

    protected $rules = [
        'name' => 'required|string|max:200',
        'username' => 'required|string|alpha_dash|unique:users',
        'password' => 'required|string|min:8',
        'role' => 'required|string|in:admin,super-admin'
    ];

    private function resetInputFields(){
        $this->name = '';
        $this->username = '';
        $this->password = '';
        $this->role = '';
    }

    public function store() 
    {
        $validatedData = $this->validate();

        $user = User::create([
            'name' => $this->name,
            'username' => $this->username,
            'password' => bcrypt($this->password)
        ]);

        $user->assignRole($this->role);

        session()->flash('message', 'Admin Created Successfully.');

        activity()->log("Admin Created: $user->name");

        $this->resetInputFields();

        $this->emit('employeeStore'); // Close model to using to jquery
    }

    public function edit($id) 
    {
        $this->updateMode = true;
        $user = User::where('id', $id)->first();
        $this->user_id = $id;

        $this->name = $user->name;
        $this->username = $user->username;
        $this->password = '';
        $this->role = $user->getRoleNames()->first();
    }

    public function update()
    {
        $this->rules['username'] = 'required|string|alpha_dash|unique:users,username,' .$this->user_id;
        $this->rules['password'] = 'nullable|string|min:8';
       
        $validatedData = $this->validate();

        if ($this->user_id) {
            $user = User::find($this->user_id);
            $old = User::find($this->user_id);

            $array = [
                'name' => $this->name,
                'username' => $this->username,
                'password' => bcrypt($this->password)
            ];

            if (!$this->password) {
                $array = Arr::except($array, ['password']);
            }

            $user->syncRoles([$this->role]);
            $user->update($array);
            
            $this->updateMode = false;
            activity()->withProperties(['old' => $old, 'new' => $user->refresh()])->log("Admin  Updated: $user->name");
            session()->flash('message', 'Admin Updated Successfully.');
            $this->resetInputFields();
            $this->emit('employeeUpdate'); // Close model to using to jquery

        }
    }

    public function cancel() 
    {
        $this->updateMode = false;
        $this->resetInputFields();
    }

    public function delete($id)
    {

        if(auth()->user()->id === $id) 
        {
            $this->emit('adminDeleteWarning');
            return;
        }

        if($id){
            $user = User::findOrFail($id);
            activity()->withProperties(['deleted' => $user])->log("Admin Deleted: $user->name");
            $user->delete();
            session()->flash('message', 'Admin Deleted Successfully.');
        }
    }


    public function render()
    {
        $admins = User::role(['admin', 'super-admin'])->simplePaginate(10);
        
        return view('livewire.admin.show-admins', compact('admins'));
    }
}

app/Http/Livewire/Department/ShowDepartments.php
<?php

namespace App\Http\Livewire\Department;

use Livewire\Component;
use App\Models\Department;

class ShowDepartments extends Component
{

    public $name;
    public $user_id;
    public $departments;
    public $updateMode = false;
    public $search = '';

    protected $rules = [
        'name' => 'required|max:200',
    ];

    private function resetInputFields(){
        $this->name = '';
    }


    public function store() 
    {
        $validatedData = $this->validate();

        $department = Department::create($validatedData);

        activity()->log("Department Created: $department->name");

        session()->flash('message', 'Deparment Created Successfully.');

        $this->resetInputFields();

        $this->emit('deparmentStore'); // Close model to using to jquery

    }

    public function edit($id)
    {
        $this->updateMode = true;
        $department = Department::where('id',$id)->first();
        $this->user_id = $id;
        $this->name = $department->name;
    }

    public function update()
    {
        $validatedData = $this->validate();

        if ($this->user_id) {

            $old = Department::find($this->user_id);

            $department = Department::find($this->user_id);

            $department->update([
                'name' => $this->name
            ]);

            $this->updateMode = false;

            activity()->withProperties(['old' => $old, 'new' => $department->refresh()])->log("Department Updated: $department->name");
            
            session()->flash('message', 'Department Updated Successfully.');
            $this->resetInputFields();

            $this->emit('deparmentUpdate'); // Close model to using to jquery

        }
    }

    public function cancel()
    {
        $this->updateMode = false;
        $this->resetInputFields();
    }

    public function delete($id)
    {
        if($id){
            $department = Department::findOrFail($id);
            $department->user()->update(['department_id' => null]);
            activity()->withProperties(['deleted' => $department])->log("Department Deleted: $department->name");
            $department->delete();
            session()->flash('message', 'Deparment Deleted Successfully.');
        }
    }


    public function render()
    {
        $this->departments = Department::where('name', 'like', '%'.$this->search.'%')->get();
        return view('livewire.department.show-departments');
    }
}

app/Http/Livewire/Employee/Show.php
<?php

namespace App\Http\Livewire\Employee;
use Livewire\WithPagination;
use Livewire\Component;
use App\Models\User;
use App\Models\TimeEntry;

class Show extends Component
{
    use WithPagination;

    public $user; 

    public function render()
    {
        $time_entries = TimeEntry::whereUserId($this->user->id)->orderBy('created_at','desc')->simplePaginate(20);
        return view('livewire.employee.show', compact('time_entries'));
    }
}

app/Http/Livewire/Profile/ShowProfile.php
<?php

namespace App\Http\Livewire\Profile;

use Livewire\Component;
use App\Models\User;
use Illuminate\Support\Arr;

class ShowProfile extends Component
{
    public $user_id;
    public $name;
    public $username;
    public $password;
    public $mobile_number;

    protected $rules = [
        'name' => 'required|string|max:200',
        'username' => 'required|string|alpha_dash|unique:users',
        'password' => 'required|string|min:8',
        'mobile_number' => 'nullable|regex:/(^(09)\d{9}$)+/|unique:users'
    ];

    private function resetInputFields(){
        $this->name = '';
        $this->username = '';
        $this->password = '';
        $this->mobile_number = '';
    }

    public function edit($id)
    {

        $user = User::where('id', $id)->first();
        $this->user_id = auth()->user()->id;
        $this->name = $user->name;
        $this->position = $user->position;
        $this->mobile_number = $user->mobile_number;
        $this->username = $user->username;
        $this->password = '';
    }

    public function update()
    {
        $this->rules['username'] = 'required|string|alpha_dash|unique:users,username,' .$this->user_id;
        $this->rules['mobile_number'] = 'nullable|regex:/(^(09)\d{9}$)+/|unique:users,mobile_number,' .$this->user_id;
        $this->rules['password'] = 'nullable|string|min:8';
        

        $validatedData = $this->validate();

        if ($this->user_id) {
            $user = User::find($this->user_id);
            $old = User::find($this->user_id);

            $array = [
                'name' => $this->name,
                'mobile_number' => $this->mobile_number,
                'username' => $this->username,
                'password' => bcrypt($this->password),
            ];

            if (!$this->password) {
                $array = Arr::except($array, ['password']);
            }

            if (!$this->mobile_number) {
                $array = Arr::except($array, ['mobile_number']);
            }

            $user->update($array);
            $this->updateMode = false;
            activity()->withProperties(['old' => $old, 'new' => $user->refresh()])->log("Profile  Updated: $user->name");
            session()->flash('message', 'Profile Updated Successfully.');
            $this->resetInputFields();
            $this->emit('employeeUpdate'); // Close model to using to jquery

        }
    }

    public function cancel()
    {

    }

    public function render()
    {
        $user = User::findOrFail(auth()->user()->id);

        return view('livewire.profile.show-profile', compact('user'));
    }

    
}

app/Http/Livewire/ShowTimer.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class ShowTimer extends Component
{
    public function render()
    {
        return view('livewire.show-timer');
    }
}

resources/views/livewire/employee/create.blade.php
<button class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" data-toggle="modal" data-target="#exampleModal" wire:click.prevent="cancel()">
    <i class="fas fa-plus fa-sm text-white-50"></i>  Create Personnel
</button>



<!-- Modal -->
<div wire:ignore.self class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create Personnel</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                     <span aria-hidden="true close-btn">×</span>
                </button>
            </div>
           <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Name</label>
                        <input type="text" class="form-control  @error('name') is-invalid @enderror" placeholder="Enter Employee Name" wire:model.defer="name">
                        @error('name') <span class="invalid-feedback text-left">{{ $message }}</span>@enderror
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Username</label>
                        <input type="text" class="form-control  @error('username') is-invalid @enderror" placeholder="Enter Username" wire:model.defer="username">
                        @error('username') <span class="invalid-feedback text-left">{{ $message }}</span>@enderror
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Password</label>
                        <input type="password" class="form-control  @error('password') is-invalid @enderror" placeholder="Enter Password" wire:model.defer="password">
                        @error('password') <span class="invalid-feedback text-left">{{ $message }}</span>@enderror
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Postion</label>
                        <input type="text" class="form-control  @error('position') is-invalid @enderror"  placeholder="Enter Position Name" wire:model.defer="position">
                        @error('position') <span class="invalid-feedback text-left">{{ $message }}</span>@enderror
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Department</label>
                        <select class="form-control @error('department') is-invalid @enderror" aria-label="Default select example" wire:model.defer="department">
                            <option selected>Select Department</option>
                            @foreach($departments as $dept)
                                <option value="{{ $dept->id }}">{{ $dept->name }}</option>
                            @endforeach
                        </select>
                        @error('department') <span class="invalid-feedback text-left">{{ $message }}</span>@enderror
                       
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Mobile Number</label>
                        <input type="text" class="form-control @error('mobile_number') is-invalid @enderror"  placeholder="ex. 0928111555" wire:model="mobile_number">
                        @error('mobile_number') <span class="invalid-feedback text-left">{{ $message }}</span>@enderror
                       
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary close-btn" data-dismiss="modal">Close</button>
                <button type="button" wire:click.prevent="store()" class="btn btn-primary close-modal">Save changes</button>
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script type="text/javascript">
    window.livewire.on('employeeStore', () => {
        $('#exampleModal').modal('hide');
     });
</script>
@endpush

resources/views/livewire/employee/show.blade.php
    <div class="main-body">
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://ui-avatars.com/api/?name={{$user->name}}" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ $user->name }}</h4>
                      <p class="text-secondary mb-1">{{ $user->position ? $user->position : 'N/A' }}</p>
                      {{-- <button class="btn btn-primary">Follow</button>
                      <button class="btn btn-outline-primary">Message</button> --}}
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3 visible-print align-items-center text-center">
                @if(config('app.env') === 'local') 
                  {!! QrCode::size(150)->margin(5)->generate("employee_id:$user->id") !!}
                @else 
                  

                  <img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->merge('https://portal.bulan4706.com/assets/img/logo.png', .17, true)
                    ->margin(5)->size(300)
                    ->errorCorrection('H')
                    ->generate("employee_id:$user->id")) !!}">
                  {{-- <img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->margin(5)->size(150)->generate("employee_id:$user->id")) !!}"> --}}
                @endif
                <p>Personnel QR Code</p>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ ucfirst($user->name) }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ ucfirst($user->mobile_number) }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Position</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ $user->position ? $user->position : 'N/A' }}
                    </div>
                  </div>

                  <hr>

                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Department</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ $user->department ? $user->department : 'N/A' }}
                    </div>
                  </div>
                </div>
              </div>
              <div class="row gutters-sm">
                <div class="col-sm-12 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                        <h5 class="d-flex align-items-center mb-3">Time Entries</h5>
                          
                        <div class="table-responsive">
                          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    {{-- <th>ID</th> --}}
                                    <th>Name</th>
                                    <th>Date</th>
                                    <th>Day</th>
                                    <th>Time In</th>
                                    <th>Time Out</th>
                                    <th></th>
                                    <th>Time In</th>
                                    <th>Time Out</th>
                                    {{-- <th>Status</th> --}}
                                    <th>Total</th>
                                    
                                </tr>
                            </thead>
                            
                            <tbody>
                                @foreach($time_entries as $time_entry)
                                    <tr>
                                        {{-- <td>{{ $time_entry->id }}</td> --}}
                                        <td>{{ $time_entry->user->name }}</td>
                                        <td>{{ optional($time_entry->created_at)->format('F j, Y') }}</td>
                                        <td>{{ optional($time_entry->created_at)->format('l') }}</td>
                                        <td>{{ optional($time_entry->time_in_am)->format('g:i A') }}</td>
                                        <td>{{ optional($time_entry->time_out_am)->format('g:i A') }}</td>
                                        <td>&nbsp;</td>
                                        <td>{{ optional($time_entry->time_in_pm)->format('g:i A') }}</td>
                                        <td>{{ optional($time_entry->time_out_pm)->format('g:i A') }}</td>
                                        {{-- <td>
                                            @if(optional($time_entry)->time_in_status)
                                                <span class="badge badge-pill badge-success">On Time</span>
                                            @else
                                            <span class="badge badge-pill badge-danger">Late</span>
                                            @endif                                
                                        </td> --}}
                                        <td>{{ optional($time_entry)->total_time }}</td>
                                        
                                    </tr>
                                @endforeach

                                @if($time_entries->isEmpty())
                                  <tr><td colspan="11">No Available Data</td></tr>
                                @endif

                            </tbody>
                          </table>    

                          
                        </div>         
                        
                        <div class="row">
                          <div class="col-sm-12 col-md-12">
                              <div class="d-flex align-items-end flex-column">
                                  {{ $time_entries->links() }}
                              </div>
                          </div>
                        </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-sm-12 col-md-12">
                        <div class="d-flex align-items-end flex-column">
                            {{ $time_entries->links() }}
                        </div>
                    </div>
                   
                    </div>
                </div>
               
              </div>
            </div>
          </div>
        </div>
    </div>